SQL
eugene-okulik/Vlad30913 pull request #14
Opened 2024-07-21 08:44 UTC by Vladshambaryan

2024-07-21 08:51 UTC, Vladshambaryan commented
В начале надо было создать групу а потом студента.  И все получилось как ты написал.  
В задании написано в такой очереди 

1.Создайте студента (student)
2.Создайте несколько книг (books) и укажите, что ваш созданный студент взял их
3.Создайте группу (group) и определите своего студента туда
4.Создайте несколько учебных предметов (subjects)
5.Создайте по два занятия для каждого предмета (lessons)
6.Поставьте своему студенту оценки (marks) для всех созданных вами занятий

Наверно это специально :))

2024-07-21 08:59 UTC, Vladshambaryan commented
Я проверял и чистил базу после себя поэтому в коде много select  и delete да и понаблюдать.

2024-07-22 08:36 UTC, eugene-okulik commented
> В начале надо было создать групу а потом студента. И все получилось как ты написал. В задании написано в такой очереди
> 
> 1.Создайте студента (student) 2.Создайте несколько книг (books) и укажите, что ваш созданный студент взял их 3.Создайте группу (group) и определите своего студента туда 4.Создайте несколько учебных предметов (subjects) 5.Создайте по два занятия для каждого предмета (lessons) 6.Поставьте своему студенту оценки (marks) для всех созданных вами занятий
> 
> Наверно это специально :))

Это сделано специально - сначала студента потом группу. Тогда появляется практика для Update и узнаешь, что если поле нечем заполнить, то можно его или не заполнять или заполнить значением NULL

2024-07-22 08:37 UTC, eugene-okulik requested changes
Сейчас ты изменил задание под решение, а нужно делать решение, соответствующее заданию.

2024-07-22 11:07 UTC, Vladshambaryan commented
Я не пойму на уроке ты говориш сначала группу а потом студента .

2024-07-22 14:41 UTC, eugene-okulik commented
> Я не пойму на уроке ты говориш сначала группу а потом студента .

На уроке я не даю задание. Просто объясняю где чего не хватает. А в задании четко пишу что нужно сделать.

2024-07-22 14:46 UTC, eugene-okulik commented on homework/vlad_shambaryan/Homework_14/task_sql.sql
Теперь ты не определяешь своего студента в группу. У тебя раньше здесь бы код, который изменял студента, добавляя ему группу. А сейчас этого кода нет.

2024-07-22 18:02 UTC, Vladshambaryan commented
подскажи как чистить базу я там сотни студентов  размножил

2024-07-23 09:01 UTC, eugene-okulik approved these changes

2024-07-23 09:01 UTC, merged