3 tasks about indexes and slices
eugene-okulik/Vlad30913 pull request #4
Opened 2024-07-09 10:02 UTC by Vladshambaryan

По второму заданию я бы хотел получить обьяснения  но решил как смог с помощю гугла

2024-07-09 10:11 UTC, eugene-okulik requested changes

2024-07-09 10:11 UTC, eugene-okulik commented on homework/vlad_shambaryan/Homework_5/task_2.py
> +index2 = int(result2[20:25]) + 10  # получение числа, прибавление 10
В примерах - варианты того, как может ответить программа. Вместо числа 42 может оказаться число 28346473, вместо 514 число 3. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.  
Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-07-09 10:53 UTC, Vladshambaryan commented on homework/vlad_shambaryan/Homework_5/task_2.py
> +index2 = int(result2[20:25]) + 10  # получение числа, прибавление 10
task 2  код вроде универсальный сразными даными работает и прибавляет 10

2024-07-09 16:44 UTC, Vladshambaryan commented on homework/vlad_shambaryan/Homework_5/task_2.py
> +index2 = int(result2[20:25]) + 10  # получение числа, прибавление 10
git push  прошел успешно проверь task 2

2024-07-09 16:52 UTC, Vladshambaryan commented on homework/vlad_shambaryan/Homework_5/task_2.py
> +index2 = int(result2[20:25]) + 10  # получение числа, прибавление 10
Женя  проверь  или прокоментируй сижу жду

2024-07-10 08:20 UTC, eugene-okulik approved these changes
:+1:

2024-07-10 08:20 UTC, merged