decorators
eugene-okulik/Vlad30913 pull request #9
Opened 2024-07-15 07:40 UTC by Vladshambaryan

2024-07-15 10:13 UTC, eugene-okulik requested changes
Первый - круто, жду остальные. И там линт еще ошибку одну выдает.

2024-07-15 10:28 UTC, Vladshambaryan commented
А что сделать чтоб lint не выдал ошибку. ?Остальные тоже готово я отменил  потому что ругается но всё соответствует pep 8. Ещё про 3 задание в обычном калькуляторе (-10 * 3 = -30) а в pycharm -0.3

2024-07-15 11:46 UTC, eugene-okulik commented
> А что сделать чтоб lint не выдал ошибку. ?Остальные тоже готово я отменил потому что ругается но всё соответствует pep 8. Ещё про 3 задание в обычном калькуляторе (-10 * 3 = -30) а в pycharm -0.3

В видео, которое шло к  третьему занятию  (Lesson 3), где-то со времени 1 ч 25 мин я рассказываю как разбираться с проблемами, которые возникают с Lint.

2024-07-15 11:47 UTC, eugene-okulik commented
> Ещё про 3 задание в обычном калькуляторе (-10 * 3 = -30) а в pycharm -0.3

Результат не так важен, как правильный код.

2024-07-15 19:04 UTC, Vladshambaryan commented
Спасибо за все и за  lesson 3 .  Надеюсь доступ к видео  останется чтоб освежить иногда.

2024-07-16 08:18 UTC, eugene-okulik commented
> Спасибо за все и за lesson 3 . Надеюсь доступ к видео останется чтоб освежить иногда.

Конечно. Навсегда.

2024-07-16 08:21 UTC, eugene-okulik approved these changes

2024-07-16 08:21 UTC, eugene-okulik commented on homework/vlad_shambaryan/Homework_10/task_4.py
> +items_dict = {item.split()[0]: int(item.split()[1].strip('р')) for item in PRICE_LIST.split('\n')}
О, круто, что прям одной строкой. Но учти - вот это решение хорошо для практики во время обучения. Если ты в работе сделаешь такое однострочное решение - могут руки оторвать ))))  
Проблема его в том, что очень сложно понять что в этом коде происходит. Чисто для лучшей читаемости правильнее будет сделать такое циклами - там всё более наглядно.

2024-07-16 08:21 UTC, merged